- name: omero searchengine | index containers
  become: yes
  community.docker.docker_container:
    image: "{{ searchengine_docker_image }}"
    name: "index_container_{{ container_type }}{{ ids | default(omit) }}"
    cleanup: True
    command: "index_container_from_database -d {{ default_datasource }} -r {{ container_type }}  -i {{ ids }}"
    networks:
      - name: "{{ searchengine_network }}"
    #restart: "{{ searchengine_conf_status | changed }}"
    state: started
    volumes:
      - "{{ apps_folder }}/searchengine/searchengine/:/etc/searchengine/"
      - "{{ apps_folder }}/searchengine/searchengine/cachedata:/etc/searchengine/cachedata"
      - "{{ apps_folder }}/searchengine/searchengine/logs/:/opt/app-root/src/logs/"
      - "{{ apps_folder }}/data_dump:{{ apps_folder }}/data_dump"